export default {
  // TODO: these should be part of AppActionTypes
  // generic
  CLEAR_SELECTED_ITEMS: 'CLEAR_SELECTED_ITEMS',
  RESET: 'RESET',
  RECEIVE_SERIALIZED_DATA: 'RECEIVE_SERIALIZED_DATA',
  SET_TEMPLATE: 'SET_TEMPLATE',
  SET_TEMPLATE_OPTIONS: 'SET_TEMPLATE_OPTIONS',
  RESTORE_DEFAULT_TEMPLATE_AND_OPTIONS: 'RESTORE_DEFAULT_TEMPLATE_AND_OPTIONS',
  // end-TODO

  // messages
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  UNDO_DELETE_MESSAGE: 'UNDO_DELETE_MESSAGE',
  RECEIVE_RAW_MESSAGES: 'RECEIVE_RAW_MESSAGES',

  // mailboxes
  SELECT_MAILBOX: 'SELECT_MAILBOX',
  RECEIVE_RAW_MAILBOXES: 'RECEIVE_RAW_MAILBOXES',

  // contributors
  RECEIVE_RAW_CONTRIBUTORS: 'RECEIVE_RAW_CONTRIBUTORS'
};
