module.exports = {
  // messages
  SELECT_MESSAGE: 'SELECT_MESSAGE',
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  UNDO_DELETE_MESSAGE: 'UNDO_DELETE_MESSAGE',
  RECEIVE_RAW_MESSAGES: 'RECEIVE_RAW_MESSAGES',

  // mailboxes
  SELECT_MAILBOX: 'SELECT_MAILBOX',
  RECEIVE_RAW_MAILBOXES: 'RECEIVE_RAW_MAILBOXES',

  // contributors
  RECEIVE_RAW_CONTRIBUTORS: 'RECEIVE_RAW_CONTRIBUTORS'
};
