module.exports = {
  messages: [
    {"id": 1, "mailbox_id": 1, "from": "Guy 1", "to": "Dan", "subject": "React", "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris porta feugiat ligula, non blandit metus viverra quis. Nullam non blandit sapien, et dignissim metus. Sed laoreet vel metus id mattis. Nunc mollis viverra massa efficitur scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent laoreet neque in imperdiet aliquet. Cras id velit et mi dignissim laoreet et et est. Pellentesque vitae auctor nulla, in consectetur nunc. Nam convallis mollis laoreet."},
    {"id": 2, "mailbox_id": 1, "from": "Guy 2", "to": "Dan", "subject": "React again", "body": "Nulla libero ex, iaculis non auctor sed, rhoncus a tortor. Nullam sit amet velit turpis. Pellentesque mollis, sem sed finibus porttitor, odio est tincidunt felis, maximus ornare tortor lectus mollis odio. Proin id metus tincidunt, mollis nibh sed, fermentum ex. Donec quis enim at lorem varius laoreet. Morbi turpis turpis, ullamcorper eu aliquet non, suscipit nec nisl. Mauris consequat condimentum nulla non tincidunt. Vestibulum hendrerit vestibulum turpis, in dapibus turpis. Aenean consectetur sem ante. Vivamus et aliquet massa, eu rutrum diam. Vivamus venenatis fringilla fringilla. Integer sed justo pellentesque, ullamcorper metus vel, egestas diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam convallis neque eu arcu imperdiet tincidunt. Phasellus ac urna et velit placerat sagittis fringilla ut eros. Maecenas ultricies nulla ut aliquet laoreet."},
    {"id": 3, "mailbox_id": 3, "from": "Guy 3", "to": "Dan", "subject": "Angular?", "body": "Intege et mauris porta, sagittis diam quis, dictum est. Sed quis neque a purus feugiat luctus eu a nulla. Vivamus convallis enim ac metus finibus, a viverra erat consectetur. Sed quis justo at leo vestibulum consectetur. Vestibulum nec nisl fringilla, pulvinar tortor vitae, sollicitudin nisi. Nam congue libero in neque laoreet tempus. Praesent congue euismod leo sed rutrum. Sed vulputate neque eu mauris finibus varius. Quisque vitae tortor neque. Mauris auctor risus tortor, vitae tincidunt ligula semper id. Pellentesque nec mi nec nisi imperdiet euismod. Curabitur feugiat nisi ac hendrerit lacinia. Sed sed mi a nisi sagittis mollis."},
    {"id": 4, "mailbox_id": 3, "from": "Guy 3", "to": "Dan", "subject": "Foundation?", "body": "Integer non sapien sit amet justo viverra scelerisque vel ac sapien. Morbi posuere, diam ut scelerisque condimentum, nisl eros viverra odio, nec vehicula purus lorem ut dolor. Nam ut nisi laoreet, tincidunt tortor tincidunt, consequat purus. Duis nunc nibh, lobortis non facilisis ac, varius sit amet est. Pellentesque id sodales dui. Nulla vel semper quam. Praesent auctor pharetra gravida. Sed vestibulum at orci eu rhoncus. Maecenas pellentesque ut mi vel aliquam. Integer vestibulum molestie finibus. Cras pellentesque at ligula a consequat."},
    {"id": 5, "mailbox_id": 3, "from": "Guy 4", "to": "Dan", "subject": "Webpack?", "body": "Suspendisse euismod nunc nec leo tristique dictum. Morbi a neque sed erat pulvinar aliquet at vel sapien. Fusce elementum ligula sit amet efficitur tempor. Nunc auctor enim id commodo pharetra. Nulla pellentesque fringilla ligula ac viverra. Maecenas euismod ligula turpis, ac laoreet metus elementum sit amet. Mauris mattis euismod dolor, vitae mollis ante pulvinar ut. Suspendisse pulvinar et lacus nec placerat. Vestibulum at aliquet magna. Aenean at ultricies ligula, et molestie erat. Sed feugiat augue et velit euismod laoreet. Curabitur lacinia massa nec viverra lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus."}
  ]
}
