#!/bin/bash

out=_build
out_js=_build_js

rm -rf $out $out_js
mkdir $out_js

(broccoli-timepiece $out) &
(watchify app/client.js -d -v -o $out_js/app.js -t [ babelify --only app ]) &
(BUILD_DIR=$out BUILD_JS_DIR=$out_js node web.js) &

wait
