#!/bin/bash

out=_build
out_js=_build_js

rm -rf $out $out_js
mkdir $out_js

(broccoli-timepiece $out) &
(watchify app/client.js -d -v -o $out_js/app.js -t [ babelify --only app ]) &
(node fixture-api.js) &
(babel-node ./app/server.js) &

wait
